language: ruby
rvm:
- 2.3.0
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: ElD7qX/7u/lipwOX2gT7rhw9dTKUqOnDyP4ap6RXKxyRn4tEdysFs0SyAb6uWmpBDIZXudrMh6gDYT8Xarv06NvA0JbFuxhaHDg3rkm/OFQ7TWqn96hFPH3hQ3ppAYLeydRxtSh7KOUU0NKAzS9yYtfqwOJg0wBFY5u3LBdLUrmuz9kPGmm+e11Y0BeAlfSZatRWIsJ3IfWD7Z1N4AD6qhgmZfvSK2KMRIr2FOK1kFCdKdA4zjgQSDW6/8neWSauKGh8xrZqEi8MU4V7JUKDtEbeIizNuoB95pznJAf471eFcVASDApXcU5GoGH7m1dBO4eKUyXEV/xfwKakLkqJGl3sXCvaeLjvTxY0cM6ZYUzN+mrH5l7A1Gw2RzjyWfctQd7XDfXtFjozYRKBLyRZypK2DlYp11qtOrIGe22r/bqVfy78Io8iYeh9b7HogfX2hWdpAIDnoubmBnyH+xdC4BaWQFgojGlxTsuMeFGSktcZExhinBLBaNGdxeQHk+td9CIz8ZFL1zVD0R1YUzkBjnaLyxwUkv6eEdbc2uP33Z8MlQf/YvRuRjEDubBWsh4Sqbv8ra42QvrhPnzjEsXZ71xPTGoyRXLZ7UckeDlRbf8BQk2Ml7CJZ4CYbLEoipVep00p47UQ5yHe6l++NQvoIZq3wqfzYaixzHESkag4RzI=
  app: sking-chirpit
  on:
    repo: skylarking/ChirpIt
  run:
    - "rake db:migrate"
addons:
  code_climate:
      repo_token: ac3803c2fe1333a0923e45db7d74ae3dec7b842e304f95d8e7d114b470c6ee9e
notifications:
  email: false
